# Generated by Django 5.1 on 2024-09-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_color_marca_proveedor_tamano_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('numero_comprobante', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tamaño',
            new_name='tamano',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('tipo_venta', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.cliente')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.comprobante')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tienda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='VentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuotas', models.IntegerField()),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_limite', models.DateField()),
                ('saldo_restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.venta')),
            ],
        ),
    ]
