# Generated by Django 5.1 on 2024-09-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_cliente_comprobante_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.venta')),
            ],
        ),
    ]
