# Generated by Django 5.1 on 2024-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
