# Generated by Django 5.1 on 2024-09-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_producto_descripcion_venta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tienda'),
        ),
        migrations.AlterField(
            model_name='ventacredito',
            name='interes',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.ventacredito')),
            ],
        ),
    ]
