# Generated by Django 5.1 on 2024-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagocredito',
            old_name='venta',
            new_name='venta_credito',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
