# Generated by Django 5.1 on 2024-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_venta_pagocredito_venta_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
