# Generated by Django 5.1 on 2024-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacredito',
            name='frecuencia_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=10),
            preserve_default=False,
        ),
    ]
